#pragma line 1 "src/Envelope.cpp" ::: 0
#pragma line 1 "src/Envelope.cpp" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 155 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 11
#pragma line 145 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 64
#pragma line 156 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 67
#pragma line 413 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 197
#pragma line 427 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 200
#pragma line 7 "<command line>" 2 ::: 202
#pragma line 1 "<built-in>" 2 ::: 203
#pragma line 1 "src/Envelope.cpp" 2 ::: 204
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 205
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 233
#pragma line 122 "/usr/include/features.h" 3 4 ::: 330
#pragma line 156 "/usr/include/features.h" 3 4 ::: 355
#pragma line 180 "/usr/include/features.h" 3 4 ::: 357
#pragma line 191 "/usr/include/features.h" 3 4 ::: 360
#pragma line 343 "/usr/include/features.h" 3 4 ::: 391
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 395
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 430
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 437
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 460
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 501
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 507
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 525
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 531
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 535
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 537
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 541
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 551
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 604
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 645
#pragma line 346 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 670
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 694
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 695
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 697
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 699
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 700
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 725
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 736
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 741
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 742
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 743
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 750
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 786
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 789
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 791
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 819
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 821
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 823
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 884
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 891
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 909
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 914
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 925
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 994
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 1008
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 1011
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1012
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1044
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1060
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1085
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1088
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1093
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1115
#pragma line 900 "/usr/include/wchar.h" 3 4 ::: 1136
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1139
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1150
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1160
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1162
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1166
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1215
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1216
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1222
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1224
#pragma line 173 "/usr/include/libio.h" 3 4 ::: 1244
#pragma line 241 "/usr/include/libio.h" 3 4 ::: 1255
#pragma line 289 "/usr/include/libio.h" 3 4 ::: 1296
#pragma line 329 "/usr/include/libio.h" 3 4 ::: 1326
#pragma line 429 "/usr/include/libio.h" 3 4 ::: 1386
#pragma line 459 "/usr/include/libio.h" 3 4 ::: 1401
#pragma line 521 "/usr/include/libio.h" 3 4 ::: 1413
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1415
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1421
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1472
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1488
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1505
#pragma line 205 "/usr/include/stdio.h" 3 4 ::: 1537
#pragma line 297 "/usr/include/stdio.h" 3 4 ::: 1614
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 1753
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 1773
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 2026
#pragma line 818 "/usr/include/stdio.h" 3 4 ::: 2037
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 2074
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 2106
#pragma line 930 "/usr/include/stdio.h" 3 4 ::: 2173
#pragma line 942 "/usr/include/stdio.h" 3 4 ::: 2176
#pragma line 2 "src/Envelope.cpp" 2 ::: 2178
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 2179
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2212
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2237
#pragma line 33 "/usr/include/stdlib.h" 2 3 4 ::: 2240
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 1 3 4 ::: 2250
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 3 4 ::: 2279
#pragma line 42 "/usr/include/stdlib.h" 2 3 4 ::: 2297
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 1 3 4 ::: 2298
#pragma line 64 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 3 4 ::: 2354
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 2355
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/endian.h" 1 3 4 ::: 2392
#pragma line 37 "/usr/include/endian.h" 2 3 4 ::: 2394
#pragma line 59 "/usr/include/endian.h" 3 4 ::: 2398
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 1 3 4 ::: 2401
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2419
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2420
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2422
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2424
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap-16.h" 1 3 4 ::: 2432
#pragma line 36 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2450
#pragma line 56 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2453
#pragma line 96 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2456
#pragma line 61 "/usr/include/endian.h" 2 3 4 ::: 2458
#pragma line 65 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 2 3 4 ::: 2459
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 2493
#pragma line 57 "/usr/include/stdlib.h" 3 4 ::: 2499
#pragma line 83 "/usr/include/stdlib.h" 3 4 ::: 2504
#pragma line 96 "/usr/include/stdlib.h" 3 4 ::: 2506
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 2647
#pragma line 236 "/usr/include/stdlib.h" 2 3 4 ::: 2690
#pragma line 302 "/usr/include/stdlib.h" 3 4 ::: 2727
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/types.h" 1 3 4 ::: 2741
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2822
#pragma line 115 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2830
#pragma line 132 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2839
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 2840
#pragma line 58 "/usr/include/time.h" 3 4 ::: 2861
#pragma line 74 "/usr/include/time.h" 3 4 ::: 2864
#pragma line 90 "/usr/include/time.h" 3 4 ::: 2867
#pragma line 102 "/usr/include/time.h" 3 4 ::: 2870
#pragma line 133 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2873
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2888
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2913
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2916
#pragma line 186 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2926
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/select.h" 1 3 4 ::: 2961
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/select.h" 1 3 4 ::: 2992
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3015
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3017
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/select.h" 2 3 4 ::: 3019
#pragma line 31 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3020
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 3024
#pragma line 34 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3064
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 3075
#pragma line 118 "/usr/include/time.h" 3 4 ::: 3096
#pragma line 44 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3104
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 3106
#pragma line 46 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3141
#pragma line 220 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3228
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 1 3 4 ::: 3232
#pragma line 58 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 3268
#pragma line 223 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3272
#pragma line 262 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 3294
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 1 3 4 ::: 3304
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3326
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3328
#pragma line 22 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 2 3 4 ::: 3330
#pragma line 58 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3331
#pragma line 88 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3354
#pragma line 125 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3376
#pragma line 220 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3453
#pragma line 271 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3484
#pragma line 315 "/usr/include/stdlib.h" 2 3 4 ::: 3488
#pragma line 465 "/usr/include/stdlib.h" 3 4 ::: 3631
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 3660
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3685
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3710
#pragma line 25 "/usr/include/alloca.h" 2 3 4 ::: 3713
#pragma line 493 "/usr/include/stdlib.h" 2 3 4 ::: 3728
#pragma line 629 "/usr/include/stdlib.h" 3 4 ::: 3856
#pragma line 651 "/usr/include/stdlib.h" 3 4 ::: 3870
#pragma line 683 "/usr/include/stdlib.h" 3 4 ::: 3894
#pragma line 705 "/usr/include/stdlib.h" 3 4 ::: 3907
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h" 1 3 4 ::: 4158
#pragma line 955 "/usr/include/stdlib.h" 2 3 4 ::: 4176
#pragma line 967 "/usr/include/stdlib.h" 3 4 ::: 4179
#pragma line 3 "src/Envelope.cpp" 2 ::: 4181
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 4182
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 1 3 4 ::: 4214
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libm-simd-decl-stubs.h" 1 3 4 ::: 4240
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 2 3 4 ::: 4272
#pragma line 32 "/usr/include/math.h" 2 3 4 ::: 4273
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_val.h" 1 3 4 ::: 4278
#pragma line 36 "/usr/include/math.h" 2 3 4 ::: 4303
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_valf.h" 1 3 4 ::: 4305
#pragma line 38 "/usr/include/math.h" 2 3 4 ::: 4330
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_vall.h" 1 3 4 ::: 4331
#pragma line 39 "/usr/include/math.h" 2 3 4 ::: 4350
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/inf.h" 1 3 4 ::: 4354
#pragma line 42 "/usr/include/math.h" 2 3 4 ::: 4378
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/nan.h" 1 3 4 ::: 4382
#pragma line 45 "/usr/include/math.h" 2 3 4 ::: 4407
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 1 3 4 ::: 4412
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 4429
#pragma line 41 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 4435
#pragma line 49 "/usr/include/math.h" 2 3 4 ::: 4442
#pragma line 83 "/usr/include/math.h" 3 4 ::: 4448
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 4449
#pragma line 84 "/usr/include/math.h" 2 3 4 ::: 4833
#pragma line 93 "/usr/include/math.h" 3 4 ::: 4834
#pragma line 104 "/usr/include/math.h" 3 4 ::: 4837
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 4838
#pragma line 105 "/usr/include/math.h" 2 3 4 ::: 5222
#pragma line 139 "/usr/include/math.h" 3 4 ::: 5223
#pragma line 151 "/usr/include/math.h" 3 4 ::: 5226
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 5227
#pragma line 152 "/usr/include/math.h" 2 3 4 ::: 5611
#pragma line 167 "/usr/include/math.h" 3 4 ::: 5612
#pragma line 248 "/usr/include/math.h" 3 4 ::: 5679
#pragma line 268 "/usr/include/math.h" 3 4 ::: 5681
#pragma line 282 "/usr/include/math.h" 3 4 ::: 5683
#pragma line 304 "/usr/include/math.h" 3 4 ::: 5693
#pragma line 318 "/usr/include/math.h" 3 4 ::: 5695
#pragma line 346 "/usr/include/math.h" 3 4 ::: 5711
#pragma line 411 "/usr/include/math.h" 3 4 ::: 5765
#pragma line 428 "/usr/include/math.h" 3 4 ::: 5767
#pragma line 448 "/usr/include/math.h" 3 4 ::: 5771
#pragma line 470 "/usr/include/math.h" 3 4 ::: 5786
#pragma line 534 "/usr/include/math.h" 3 4 ::: 5842
#pragma line 4 "src/Envelope.cpp" 2 ::: 5844
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/hls_stream.h" 1 ::: 5845
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_enum.h" 1 ::: 5912
#pragma line 67 "/opt/Xilinx/Vivado_HLS/2017.2/common/technology/autopilot/hls_stream.h" 2 ::: 6047
#pragma line 5 "src/Envelope.cpp" 2 ::: 6153
#pragma line 1 "src/Envelope.h" 1 ::: 6154
#pragma line 6 "src/Envelope.cpp" 2 ::: 6174
