#pragma line 1 "src/Envelope.cpp" ::: -10
#pragma line 1 "src/Envelope.cpp" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 155 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/home/austin/Desktop/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 1
#pragma line 145 "/home/austin/Desktop/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 54
#pragma line 156 "/home/austin/Desktop/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 57
#pragma line 413 "/home/austin/Desktop/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 187
#pragma line 427 "/home/austin/Desktop/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 190
#pragma line 7 "<command line>" 2 ::: 192
#pragma line 1 "<built-in>" 2 ::: 193
#pragma line 1 "src/Envelope.cpp" 2 ::: 194
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 195
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 223
#pragma line 122 "/usr/include/features.h" 3 4 ::: 320
#pragma line 156 "/usr/include/features.h" 3 4 ::: 345
#pragma line 180 "/usr/include/features.h" 3 4 ::: 347
#pragma line 191 "/usr/include/features.h" 3 4 ::: 350
#pragma line 343 "/usr/include/features.h" 3 4 ::: 381
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 385
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 420
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 427
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 450
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 491
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 497
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 515
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 521
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 525
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 527
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 531
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 541
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 594
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 635
#pragma line 346 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 660
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 684
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 685
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 687
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 689
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 690
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 715
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 726
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 731
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 732
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 733
#pragma line 1 "/home/austin/Desktop/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 740
#pragma line 56 "/home/austin/Desktop/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 776
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 779
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 781
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 809
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 811
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 813
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 874
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 881
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 899
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 904
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 915
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 984
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 998
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 1001
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1002
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1034
#pragma line 1 "/home/austin/Desktop/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1050
#pragma line 56 "/home/austin/Desktop/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1075
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1078
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1083
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1105
#pragma line 900 "/usr/include/wchar.h" 3 4 ::: 1126
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1129
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1140
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1150
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1152
#pragma line 1 "/home/austin/Desktop/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1156
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1205
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1206
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1212
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1214
#pragma line 173 "/usr/include/libio.h" 3 4 ::: 1234
#pragma line 241 "/usr/include/libio.h" 3 4 ::: 1245
#pragma line 289 "/usr/include/libio.h" 3 4 ::: 1286
#pragma line 329 "/usr/include/libio.h" 3 4 ::: 1316
#pragma line 429 "/usr/include/libio.h" 3 4 ::: 1376
#pragma line 459 "/usr/include/libio.h" 3 4 ::: 1391
#pragma line 521 "/usr/include/libio.h" 3 4 ::: 1403
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1405
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1411
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1462
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1478
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1495
#pragma line 205 "/usr/include/stdio.h" 3 4 ::: 1527
#pragma line 297 "/usr/include/stdio.h" 3 4 ::: 1604
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 1743
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 1763
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 2016
#pragma line 818 "/usr/include/stdio.h" 3 4 ::: 2027
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 2064
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 2096
#pragma line 930 "/usr/include/stdio.h" 3 4 ::: 2163
#pragma line 942 "/usr/include/stdio.h" 3 4 ::: 2166
#pragma line 2 "src/Envelope.cpp" 2 ::: 2168
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 2169
#pragma line 1 "/home/austin/Desktop/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2202
#pragma line 56 "/home/austin/Desktop/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2227
#pragma line 33 "/usr/include/stdlib.h" 2 3 4 ::: 2230
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 1 3 4 ::: 2240
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 3 4 ::: 2269
#pragma line 42 "/usr/include/stdlib.h" 2 3 4 ::: 2287
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 1 3 4 ::: 2288
#pragma line 64 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 3 4 ::: 2344
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 2345
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/endian.h" 1 3 4 ::: 2382
#pragma line 37 "/usr/include/endian.h" 2 3 4 ::: 2384
#pragma line 59 "/usr/include/endian.h" 3 4 ::: 2388
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 1 3 4 ::: 2391
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2409
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2410
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2412
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2414
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap-16.h" 1 3 4 ::: 2422
#pragma line 36 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2440
#pragma line 56 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2443
#pragma line 96 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2446
#pragma line 61 "/usr/include/endian.h" 2 3 4 ::: 2448
#pragma line 65 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 2 3 4 ::: 2449
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 2483
#pragma line 57 "/usr/include/stdlib.h" 3 4 ::: 2489
#pragma line 83 "/usr/include/stdlib.h" 3 4 ::: 2494
#pragma line 96 "/usr/include/stdlib.h" 3 4 ::: 2496
#pragma line 1 "/usr/include/xlocale.h" 1 3 4 ::: 2637
#pragma line 39 "/usr/include/xlocale.h" ::: 2679
#pragma line 236 "/usr/include/stdlib.h" 2 3 4 ::: 2684
#pragma line 302 "/usr/include/stdlib.h" 3 4 ::: 2721
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/types.h" 1 3 4 ::: 2735
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2816
#pragma line 115 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2824
#pragma line 132 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2833
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 2834
#pragma line 58 "/usr/include/time.h" 3 4 ::: 2855
#pragma line 74 "/usr/include/time.h" 3 4 ::: 2858
#pragma line 90 "/usr/include/time.h" 3 4 ::: 2861
#pragma line 102 "/usr/include/time.h" 3 4 ::: 2864
#pragma line 133 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2867
#pragma line 1 "/home/austin/Desktop/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2882
#pragma line 56 "/home/austin/Desktop/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2907
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2910
#pragma line 186 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2920
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/select.h" 1 3 4 ::: 2955
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/select.h" 1 3 4 ::: 2986
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3009
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3011
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/select.h" 2 3 4 ::: 3013
#pragma line 31 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3014
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 3018
#pragma line 34 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3058
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 3069
#pragma line 118 "/usr/include/time.h" 3 4 ::: 3090
#pragma line 44 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3098
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 3100
#pragma line 46 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3135
#pragma line 220 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3222
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 1 3 4 ::: 3226
#pragma line 58 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 3262
#pragma line 223 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3266
#pragma line 262 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 3288
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 1 3 4 ::: 3298
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3320
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3322
#pragma line 22 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 2 3 4 ::: 3324
#pragma line 58 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3325
#pragma line 88 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3348
#pragma line 125 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3370
#pragma line 220 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3447
#pragma line 271 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3478
#pragma line 315 "/usr/include/stdlib.h" 2 3 4 ::: 3482
#pragma line 465 "/usr/include/stdlib.h" 3 4 ::: 3625
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 3654
#pragma line 1 "/home/austin/Desktop/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3679
#pragma line 56 "/home/austin/Desktop/Vivado_HLS/2017.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3704
#pragma line 25 "/usr/include/alloca.h" 2 3 4 ::: 3707
#pragma line 493 "/usr/include/stdlib.h" 2 3 4 ::: 3722
#pragma line 629 "/usr/include/stdlib.h" 3 4 ::: 3850
#pragma line 651 "/usr/include/stdlib.h" 3 4 ::: 3864
#pragma line 683 "/usr/include/stdlib.h" 3 4 ::: 3888
#pragma line 705 "/usr/include/stdlib.h" 3 4 ::: 3901
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h" 1 3 4 ::: 4152
#pragma line 955 "/usr/include/stdlib.h" 2 3 4 ::: 4170
#pragma line 967 "/usr/include/stdlib.h" 3 4 ::: 4173
#pragma line 3 "src/Envelope.cpp" 2 ::: 4175
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 4177
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 1 3 4 ::: 4209
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libm-simd-decl-stubs.h" 1 3 4 ::: 4235
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 2 3 4 ::: 4267
#pragma line 32 "/usr/include/math.h" 2 3 4 ::: 4268
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_val.h" 1 3 4 ::: 4273
#pragma line 36 "/usr/include/math.h" 2 3 4 ::: 4298
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_valf.h" 1 3 4 ::: 4300
#pragma line 38 "/usr/include/math.h" 2 3 4 ::: 4325
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_vall.h" 1 3 4 ::: 4326
#pragma line 39 "/usr/include/math.h" 2 3 4 ::: 4345
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/inf.h" 1 3 4 ::: 4349
#pragma line 42 "/usr/include/math.h" 2 3 4 ::: 4373
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/nan.h" 1 3 4 ::: 4377
#pragma line 45 "/usr/include/math.h" 2 3 4 ::: 4402
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 1 3 4 ::: 4407
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 4424
#pragma line 41 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 4430
#pragma line 49 "/usr/include/math.h" 2 3 4 ::: 4437
#pragma line 83 "/usr/include/math.h" 3 4 ::: 4443
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 4444
#pragma line 84 "/usr/include/math.h" 2 3 4 ::: 4828
#pragma line 93 "/usr/include/math.h" 3 4 ::: 4829
#pragma line 104 "/usr/include/math.h" 3 4 ::: 4832
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 4833
#pragma line 105 "/usr/include/math.h" 2 3 4 ::: 5217
#pragma line 139 "/usr/include/math.h" 3 4 ::: 5218
#pragma line 151 "/usr/include/math.h" 3 4 ::: 5221
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 5222
#pragma line 152 "/usr/include/math.h" 2 3 4 ::: 5606
#pragma line 167 "/usr/include/math.h" 3 4 ::: 5607
#pragma line 248 "/usr/include/math.h" 3 4 ::: 5674
#pragma line 268 "/usr/include/math.h" 3 4 ::: 5676
#pragma line 282 "/usr/include/math.h" 3 4 ::: 5678
#pragma line 304 "/usr/include/math.h" 3 4 ::: 5688
#pragma line 318 "/usr/include/math.h" 3 4 ::: 5690
#pragma line 346 "/usr/include/math.h" 3 4 ::: 5706
#pragma line 411 "/usr/include/math.h" 3 4 ::: 5760
#pragma line 428 "/usr/include/math.h" 3 4 ::: 5762
#pragma line 448 "/usr/include/math.h" 3 4 ::: 5766
#pragma line 470 "/usr/include/math.h" 3 4 ::: 5781
#pragma line 534 "/usr/include/math.h" 3 4 ::: 5837
#pragma line 4 "src/Envelope.cpp" 2 ::: 5839
#pragma line 4 "src/Envelope.cpp" ::: 5841
#pragma line 1 "/home/austin/Desktop/Vivado_HLS/2017.2/common/technology/autopilot/hls_stream.h" 1 ::: 5843
#pragma line 1 "/home/austin/Desktop/Vivado_HLS/2017.2/common/technology/autopilot/etc/autopilot_enum.h" 1 ::: 5910
#pragma line 67 "/home/austin/Desktop/Vivado_HLS/2017.2/common/technology/autopilot/hls_stream.h" 2 ::: 6045
#pragma line 5 "src/Envelope.cpp" 2 ::: 6151
#pragma line 1 "src/Envelope.h" 1 ::: 6152
#pragma line 6 "src/Envelope.cpp" 2 ::: 6172
