// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xenvelope.h"

extern XEnvelope_Config XEnvelope_ConfigTable[];

XEnvelope_Config *XEnvelope_LookupConfig(u16 DeviceId) {
	XEnvelope_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XENVELOPE_NUM_INSTANCES; Index++) {
		if (XEnvelope_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XEnvelope_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XEnvelope_Initialize(XEnvelope *InstancePtr, u16 DeviceId) {
	XEnvelope_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XEnvelope_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XEnvelope_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

