// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// CTRL_BUS
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of press
//        bit 31~0 - press[31:0] (Read/Write)
// 0x14 : reserved
// 0x18 : Data signal of attackDuration
//        bit 31~0 - attackDuration[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of decayDuration
//        bit 31~0 - decayDuration[31:0] (Read/Write)
// 0x24 : reserved
// 0x28 : Data signal of sustainAmplitude
//        bit 31~0 - sustainAmplitude[31:0] (Read/Write)
// 0x2c : reserved
// 0x30 : Data signal of releaseDuration
//        bit 31~0 - releaseDuration[31:0] (Read/Write)
// 0x34 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XENVELOPE_CTRL_BUS_ADDR_PRESS_DATA            0x10
#define XENVELOPE_CTRL_BUS_BITS_PRESS_DATA            32
#define XENVELOPE_CTRL_BUS_ADDR_ATTACKDURATION_DATA   0x18
#define XENVELOPE_CTRL_BUS_BITS_ATTACKDURATION_DATA   32
#define XENVELOPE_CTRL_BUS_ADDR_DECAYDURATION_DATA    0x20
#define XENVELOPE_CTRL_BUS_BITS_DECAYDURATION_DATA    32
#define XENVELOPE_CTRL_BUS_ADDR_SUSTAINAMPLITUDE_DATA 0x28
#define XENVELOPE_CTRL_BUS_BITS_SUSTAINAMPLITUDE_DATA 32
#define XENVELOPE_CTRL_BUS_ADDR_RELEASEDURATION_DATA  0x30
#define XENVELOPE_CTRL_BUS_BITS_RELEASEDURATION_DATA  32

